### ISSUE TITLE
Warning and error on test run

### ISSUE THREAD

**Issue by acrylian** [FilippoBoscarino/smartImageCache-Plugin-for-Zenphoto#3]
Got these two with 1.6.1a. The 2nd break it for me:

  > {2612:Mon, 20 Mar 2023 17:00:05 GMT} Zenphoto v1.6.1a
   WARNING: Undefined variable $album_actual in …/zenphoto-dev/plugins/smartImageCache/cacheImages.php on line 224
    {2612:Mon, 20 Mar 2023 17:00:05 GMT}
    ERROR: Call to a member function getName() on null in …/zenphoto-dev/plugins/smartImageCache.php on line 171

**Comment by FilippoBoscarino** [comment]
Ok
Still some unstability on main Gallery.
Try it on a sigle album, eventually with subAlbums if they exist

**Comment by acrylian** [comment]
I think the 2nd is the downstream issue of the 1st. You create the variable in an if part only but use it in the else part as well.

**Comment by FilippoBoscarino** [comment]
Uhm... no. I investigate also on this

**Comment by FilippoBoscarino** [comment]
> Is it on purpose that it uses the classic way and ignores to what mode the cachemanager is set?

I cannot reproduce this defect. Everything seems working fine for me.
I have used exactly the same method cacheManager uses for itself
`(function_exists('curl_init')&&getOption('cacheManager_generationmode')=='curl')`

Anyway I have added in the new release the evidence in the control panel on which graphic libraries and which method are used to generate cache sizes, so it is easier to check.

**Comment by acrylian** [comment]
I did try again with an album. First I get checkmarks as with the URL mode but after it is completed the images are (unnecessarily) loaded as with the classic version. The cURL mode normally does not do that to avoid that "overhead". I guess you added that as an extra check/confirmation?

![Bildschirmfoto 2023-03-21 um 11 44 08](https://user-images.githubusercontent.com/2474309/226583970-1a0c9a71-69cf-470e-bd47-6c4f6a9b90d6.jpg)
![Bildschirmfoto 2023-03-21 um 11 44 11](https://user-images.githubusercontent.com/2474309/226583978-b64d44cd-2963-4808-8b51-a6170e6fcee1.jpg)

**Comment by FilippoBoscarino** [comment]
> I guess you added that as an extra check/confirmation?

Correct.
As I specified somewhere both GDlibrary and Imagick are not completely reliable on managing big images on limited resources.
>As in my experience, using GDlibrary on large images on limited resources can carry on some faults results as images that >appeared as created, but with an half completely grey.
>With Imagick sometimes happens that file are produced as ok, but they are corrupted and not readable.
>So a human process to control results is mandatory to have a pro result on your site.

>Gallery usages is still broken

Working on it. I think I will release the new buxfixed version within today.

**Comment by acrylian** [comment]
I understand! I would always recommend to lower the image dimensions if someone constantly runs into these issue. It will just cause overload on the server if it always reaches its limits. Most website really don't need 5000x5000px fine data images in any case, not even considering HiDPI devices.

**Comment by acrylian** [comment]
> But the issue comes out if you want to directly deliver/sell HD photos.

Well, if you want to do things you should have a server capable of these things. You can't use the "cheapest" hosting and have to invest on this. You may run into other issues by for example traffic hikes. There is always a limit of improvement . In the end the server must be able to handle it.

> Here, the Image sorting tab, invokes the caching of all the images of the Album for 40 and 80 sizes.

Not sure what  you mean. Both images tabs ("images order" and "images") have no caching buttons. Both just create the backend sizes they need on the fly these page if they have not been processed.

What may make sense is to have a button to re-cache a specific image on the "images" tab.

**Comment by FilippoBoscarino** [comment]
> Both just create the backend sizes

It is what I mean. Also this apparently simple operation could slow down the Edit page loading finalize on huge pics and/or also medium crowdy Albums.
And you have to enter in another tab to check what has been done.

> What may make sense is to have a button to re-cache a specific image on the "images" tab.

Agree and I have already planned to try to create it in future releases.

>Well, if you want to do things you should have a server capable of these things.

I definitely agree. Of course I am planning to move to a new one if I achieve the goal to build up a business like that.
For now paradoxically a limited server is very useful for me in developement to tune-up processes at their best and to discover pifalls that can raise up "under pressure".

**Comment by acrylian** [comment]
> It is what I mean. Also this apparently simple operation could slow down the Edit page loading finalize on huge pics and/or also medium crowdy Albums.
> And you have to enter in another tab to check what has been done.

Well, yes, there is no way around to pre-cache. The page uses native browser lazy loading of images so technically on capable modern browsers it should not load all images in one go. 

And if you have for example have thousands images in one single album on a slower server you may run into lots of other issues speedwise.

Since I have to work on our uploader anyway, I will see if I can implement pre-generation of at least backend sizes on upload. Otherwise this has to wait for our "major release", everything I do in 1.6.x I have to do a 2nd time which eats up time.

> For now paradoxically a limited server is very useful for me in developement to tune-up processes at their best and to discover pifalls that can raise up "under pressure".

Yes, indeed.

**Comment by FilippoBoscarino** [comment]
No problem to address this point only in the 2.x release
